### ISSUE TITLE
bacteria_size_gc .ipynb issue

### ISSUE THREAD

**Issue by moldach** [widdowquinn/Teaching#9]
I'm trying to run through the bacteria.ipynb and I'm getting the following error: IOError: [Errno 2] No such file or directory: '../data/NC_018495.fna

I though maybe I needed to run the script get_data.sh from Exercises/data folder however, that file is not in there.  What do i need to do?

**Comment by widdowquinn** [comment]
Hi,

You should (on Linux, OSX, or other system where wget/bash is available) be able to get that file, and all the others needed for that notebook, by running get_data.sh in the Part_1/data/ directory. Line 31 in https://github.com/widdowquinn/Teaching/blob/master/Comparative_Genomics_and_Visualisation/Part_1/data/get_data.sh is the one that should grab the file you need.

I've just run the script myself here, and it gets the correct file from GenBank, and the iPython notebook finds that file in the correct location.

Please could you ensure that the data is downloaded to Part_1/data - it should look like this when the download is completed:

Part_1/data$ ls
MK10_draft.fasta  NC_000913.fna     NC_002695.fna     NC_010468.fna     NC_016807.fna     NC_017523.fna     NC_018497.fna     NC_022350.fna
NC_000868.fna     NC_000961.fna     NC_003413.fna     NC_010628.fna     NC_016934.fna     NC_018495.fna     NC_018498.fna     get_data.sh*
NC_000912.fna     NC_000962.fna     NC_004431.fna     NC_014500.fna     NC_017504.fna     NC_018496.fna     NC_020076.fna
